### ISSUE TITLE
nothing happens in the enchantments page

### ISSUE THREAD

**Issue by bubzilla** [Dumphey/item-editor#4]
please make it work I can't add things to my server and I'm scared it will die off

**Comment by Dumphey** [comment]
Hey there, could you upload a video to show me what is happening? I don't really mean what "nothing happens" means.

**Comment by bubzilla** [comment]
the gui clicks don't work

**Comment by bubzilla** [comment]
i will record a video now

**Comment by bubzilla** [comment]
nevermind too lazy

**Comment by bubzilla** [comment]
so basically when you press the enchant button the menu doesn't function
or if im wrong its the add a enchantment menu
